### ISSUE TITLE
kimziv你好

### ISSUE THREAD

**Issue by caymanee** [kimziv/PinYin4Objc#1]
kimziv：你好。感谢你分享你的PinYin4Objc项目，我想给你的这个加到cocoapods管理，你能把PinYin4Objc项目打一个tag吗？

**Comment by kimziv** [comment]
https://github.com/CocoaPods/Specs/pull/4132, 已经加了，打了tag

**Comment by ruzhuxiaogu** [comment]
kimziv：您好， 我使用pinyin4objc的时候，转化之后还是汉字，请问是不是我少配置了什么，运行在ios9的真机上。
